--- # -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Site settings
author: CPSC 477/577 Staff
name: CPSC 477/577
title: Natural Language Processing
email: arman.cohan@yale.edu
description: >
  Natural Language Processing - Yale University - Spring 2024
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a>
  <br/>Theme based on <a href="https://github.com/cmudeeprl"> CMU Deep RL</a>.

url: # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: armancohan
google_analytics:
youtube_channel:
rss: # notes rss
twitter_username: armancohan

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Course Notes
blog_description: The notes written by students and edited by instructors

# Pagination
paginate: 10
permalink: /notes/:title/
paginate_path: /notes/page:num/

text:
  pagination:
    newer: "Newer"
    older: "Older"

# Comments
disqus_shortname: # put your disqus shortname

# Optional features
show_social_icons: true
enable_anchorjs: true
enable_latexjs: true
enable_katex: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  announcements:
    defaults:
      layout: post
    output: true
    permalink: /announcements/:path/

announcements_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ["_pages"]
exclude: [vendor]

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-paginate
  - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.10.1"
anchorjs_version: "3.2.2"
latexjs_version: "0.11.1"

theme: jekyll-theme-slate
